const consultants = [
  {
    id: 1,
    name: 'John Doe',
    expertise: 'Web Development',
    technology: 'React',
    year: '5 vuotta',
    education: {
      degree: 'Bachelor of Computer Science',
      program: 'Web Development',
      graduationYear: 2018,
    },
    certifications: ['Certified React Developer'],
    projects: ['E-commerce platform', 'Portfolio website'],
    workExperience: 'Started in 2016',
  },
  {
    id: 2,
    name: 'Jane Smith',
    expertise: 'Data Analysis',
    technology: 'Python',
    year: '3 vuotta',
    education: {
      degree: 'Master of Data Science',
      program: 'Data Analysis',
      graduationYear: 2020,
    },
    certifications: ['Data Science Professional'],
    projects: ['Market analysis tool', 'Survey results dashboard'],
    workExperience: 'Started in 2019',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    expertise: 'UI/UX Design',
    technology: 'Python',
    year: '2 vuotta',
    education: {
      degree: 'Bachelor of Design',
      program: 'UI/UX Design',
      graduationYear: 2021,
    },
    certifications: ['Certified UX Designer'],
    projects: ['Mobile app UI', 'Website redesign'],
    workExperience: 'Started in 2021',
  },
  {
    id: 4,
    name: 'Mike Brown',
    expertise: 'DevOps',
    technology: 'AWS',
    year: '6 vuotta',
    education: {
      degree: 'Bachelor of IT',
      program: 'DevOps',
      graduationYear: 2015,
    },
    certifications: ['AWS Certified Solutions Architect'],
    projects: ['Cloud infrastructure setup', 'CI/CD pipeline automation'],
    workExperience: 'Started in 2014',
  },
  {
    id: 5,
    name: 'Sarah Connor',
    expertise: 'Cybersecurity',
    technology: 'AWS',
    year: '4 vuotta',
    education: {
      degree: 'Bachelor of Cybersecurity',
      program: 'Network Security',
      graduationYear: 2017,
    },
    certifications: ['Certified Ethical Hacker'],
    projects: ['Firewall setup', 'Penetration testing'],
    workExperience: 'Started in 2018',
  },
  {
    id: 6,
    name: 'Paul Walker',
    expertise: 'Machine Learning',
    technology: 'Figma',
    year: '3 vuotta',
    education: {
      degree: 'Master of AI',
      program: 'Machine Learning',
      graduationYear: 2021,
    },
    certifications: ['Machine Learning Specialist'],
    projects: ['Recommendation systems', 'AI chatbot'],
    workExperience: 'Started in 2020',
  },
];

export default consultants;
